// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr79ySdAJjJIiUmUrK9y26nCF_vX11KS0',
    appId: '1:572774727111:web:b38c0746d22a1fa0e02de2',
    messagingSenderId: '572774727111',
    projectId: 'wasteagram-2a244',
    authDomain: 'wasteagram-2a244.firebaseapp.com',
    storageBucket: 'wasteagram-2a244.appspot.com',
    measurementId: 'G-GRVMZMF8K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWdFaJEv22GH0N09AnLjWVWAlHMAlEohg',
    appId: '1:572774727111:android:26ad4f3e06e439f5e02de2',
    messagingSenderId: '572774727111',
    projectId: 'wasteagram-2a244',
    storageBucket: 'wasteagram-2a244.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeGQYfy3B8RkqDHpUV8ad3F0kAJf3jerc',
    appId: '1:572774727111:ios:72f3e9625e23871fe02de2',
    messagingSenderId: '572774727111',
    projectId: 'wasteagram-2a244',
    storageBucket: 'wasteagram-2a244.appspot.com',
    iosClientId: '572774727111-ohbchelu9eoivr0epvdrk3edigj99dj1.apps.googleusercontent.com',
    iosBundleId: 'edu.oregonstate.piccionj.wasteagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeGQYfy3B8RkqDHpUV8ad3F0kAJf3jerc',
    appId: '1:572774727111:ios:72f3e9625e23871fe02de2',
    messagingSenderId: '572774727111',
    projectId: 'wasteagram-2a244',
    storageBucket: 'wasteagram-2a244.appspot.com',
    iosClientId: '572774727111-ohbchelu9eoivr0epvdrk3edigj99dj1.apps.googleusercontent.com',
    iosBundleId: 'edu.oregonstate.piccionj.wasteagram',
  );
}
